### ISSUE TITLE
[EPIC] Help wanted - spell_dbc editor

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/Keira3#1190]
I'm working on the new `spell_dbc` editor by taking inspiration from https://github.com/stoneharry/WoW-Spell-Editor (of course adapting it to the Keira3 look and feel, that is completely different).

I've almost finished the "ground work", but this is a big feature I need help in many EASY tasks (most of them require only a tiny little HTML knowledge).

This is how to run Keira3 in development mode: https://github.com/azerothcore/Keira3#how-to-run-keira3-in-development-mode

List of tasks per every tab:

### Base tab

- [x] Add fields
- [x] Add unit tests
- [ ] [EASY] add tooltips
- [ ] [EASY] order fields in a way that they are more user-friendly

### Effects tab

- [x] Add fields in their separate tabs
- [x] Add unit tests
- [ ] [EASY] add tooltips
- [ ] [EASY] order fields in a way that they are more user-friendly

### Items tab

- [ ] Add fields
- [ ] Add unit tests
- [ ] [EASY] add tooltips
- [ ] [EASY] order fields in a way that they are more user-friendly

### Flags tab

- [ ] Add fields
- [ ] Add unit tests
- [ ] [EASY] add tooltips
- [ ] [EASY] order fields in a way that they are more user-friendly

### Global

to be done at the end:
- [ ] [EASY] find out where to put the missing fields (see all fields with "TODO" `spell-dbc.type.ts` )
- [ ] Add integration tests

**Comment by willkillson** [comment]
I will take a look at this one tomorrow.

**Comment by willkillson** [comment]
I have been poking around and wanted to make sure I understanding what is being asked here.

 [EASY] add tooltips -> 
Missing information such as this,
![image](https://user-images.githubusercontent.com/26101774/119910820-d476cb80-bf0c-11eb-8099-f9b4e3d356bc.png)

and none-existing tooltips such at this,
![image](https://user-images.githubusercontent.com/26101774/119910836-df316080-bf0c-11eb-9c76-214c7196b367.png)


 [EASY] order fields in a way that they are more user-friendly ->
Would this be fine to change the ordering to alphabetical?
![image](https://user-images.githubusercontent.com/26101774/119910858-f07a6d00-bf0c-11eb-8913-19b41a3fad25.png)

**Comment by willkillson** [comment]
I am not sure what a selector is. I see this,
![image](https://user-images.githubusercontent.com/26101774/119911506-3dab0e80-bf0e-11eb-849d-4dc8690c4ef7.png)

Where you click on a row and it has an indicator. The N selected / M total doesn't look like it updates in the components.

**Comment by Stifler82** [comment]
@willkillson 

https://user-images.githubusercontent.com/1884642/119947259-72ab7580-bf8f-11eb-943b-24fe614d1c13.mp4

**Comment by FrancescoBorzi** [comment]
@willkillson 

> [EASY] add tooltips ->
Missing information in the tool tips (i) such as this,

yes

> [EASY] order fields in a way that they are more user-friendly ->
Would this be fine to change the ordering to alphabetical?

mmh no, we need to find a way that is more user friendly for people... so far we have been taking inspiration from https://github.com/stoneharry/WoW-Spell-Editor (which does not mean we should make it 100% the same)

about the rest, thanks @Stifler82 for answering with that video!

**Comment by FrancescoBorzi** [comment]
@willkillson are you still planning to look into this?

**Comment by willkillson** [comment]
@FrancescoBorzi I am currently dealing with a move, but I plan to do this. If someone wants to take it then that's fine. Sorry, IRL is beating me up right now.

**Comment by FrancescoBorzi** [comment]
no worries @willkillson , thanks for letting us know ;)

**Comment by Yehonal** [comment]
Great job here!

Some suggestions:

- add the possibility (for every table) to run simplified query search by using 3 fields: 
  - field (dropdown selector)
  - operator (dropdown selector)
  - value (text or dropdown selector if the enum is available)
  
plus an AND/OR dropdown selector to add more condition to the same search

This dynamic form will then generate a **SELECT** with all the conditions above. 

This component can be generalized in a way that it works everywhere

**Comment by heyitsbench** [comment]
Are the tasks here up to date?

**Comment by FrancescoBorzi** [comment]
> Are the tasks here up to date?

@heyitsbench last time I checked yes

**Comment by alecsci** [comment]
Hi @FrancescoBorzi, 

1) Update about missing tooltip content marked with TODO:
`Base` tab -> `Mechanics` section -> 
   - ExcludeTargetAuraState
   - ExcludeCasterAuraState
   - ExcludeTargetAuraSpell
   - ExcludeCasterAuraSpell

`Effects` tab -> `Effect` section -> missing tooltips content:
  - EffectItemType_1, EffectItemType_2, EffectItemType_3

2) Also, some of the tooltips have the entire message between question mark like this:  "?Used to create a chain visual effect?"
I assume these also have to be cross-checked and adapted. 

3) Some tooltip have the same message, for e.g. `Flags` tab -> `Interrupt` flags ->  InterruptFlags, AuraInterruptFlags, ChannelInterruptFlags and maybe they should be distinguished ?
