### ISSUE TITLE
[TODO] Implement missing SAI action types

### ISSUE THREAD

**Issue by Gultask** [azerothcore/Keira3#2228]
- [ ] SMART_ACTION_SET_CORPSE_DELAY
- [ ] SMART_ACTION_DISABLE_EVADE
- [ ] SMART_ACTION_GO_SET_GO_STATE
- [ ] SMART_ACTION_SET_CAN_FLY

https://github.com/azerothcore/wiki/issues/881
