### ISSUE TITLE
3.0.0 release progress tracking

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/Keira3#66]
This is the list of features that needs to be implemented in order to complete the **3.0.0** milestone.

Until 3.0.0, we will publish intermediate [releases](https://github.com/azerothcore/Keira3/releases), so you can already use Keira3 and give us feedback.

The features below are marked as DONE once we have them in `master` branch (they are not immediately released, so this list might differ from what is currently available in the latest release available).

### Feature editors

- [x] Creature
- [x] Quest 
- [x] Gameobject
- [x] Item
- [x] Gossip
- [x] Conditions
- [x] SmartAI

### OS Support

- [x] GNU/Linux
- [x] macOS
- [x] Windows

### Enhancements

- [ ] Item editor preview
- [ ] Item icons in all editors

### Internal technical/development features

- [x] Base classes re-used for all editors/selectors/etc...
- [x] Automated unit test full coverage 
- [x] Automated integration tests covering all editors
- [x] Dependencies always updated to latest stable version via automated dependency-updater
- [x] Debug mode toggle feature (show queries in console for easy debug)
- [x] Querying MySQL
- [x] Querying sqlite

## Support us

I and @Helias  are working for free during our free time, you can [support us with a donation](https://www.paypal.me/francesco92dev).
